# Generated by Django 3.2.9 on 2021-11-30 02:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogModel',
            new_name='Blog',
        ),
        migrations.RenameModel(
            old_name='CategoryModel',
            new_name='Category',
        ),
    ]
